apiVersion: v1
kind: ConfigMap
metadata:
  name: userdb-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "8129"
  POSTGRES_DB: users
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-database
spec:
  selector:
    matchLabels:
      app: userdb
  serviceName: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
      - name: user-database
        image: postgres:16
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: userdb-config
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: userdb-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: userdb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: userdb
  ports:
  - port: 5432
    targetPort: 5432
